image: archlinux
repositories:
  sr.ht: https://mirror.sr.ht/archlinux/sr.ht/#1ED4E14494433AE3FD302CAB74B4BCCEA60D0437
packages:
  - sassc
  - python-setuptools
  - python-srht
  - python-celery
  - python-aiosmtpd
  - python-asyncpg
  - python-redis
  - rsync
  - pacman-contrib
sources:
  - https://git.sr.ht/~sircmpwn/lists.sr.ht
  - https://git.sr.ht/~sircmpwn/sr.ht-pkgbuilds
environment:
  repo_server: deploy@mirror.sr.ht
  repo_path: /var/www/mirror.sr.ht/archlinux/sr.ht
  master: deploy@lists.sr.ht
  mailer: deploy@mail.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018 # ssh deploy key
  - 3e65a1a8-a20f-4f6b-a452-df2ac398bc1e # package signing key
tasks:
  - build: |
      cd lists.sr.ht
      ./setup.py build
  - archive: |
      cd lists.sr.ht
      pkgver=$(git describe | sed -e 's/-/_/g')
      echo "pkgver=$pkgver" >> ~/.buildenv
      git archive -o ~/sr.ht-pkgbuilds/lists.sr.ht/lists.sr.ht-$pkgver.tar.xz \
        --prefix=lists.sr.ht-$pkgver/ HEAD
  - package: |
      cd sr.ht-pkgbuilds/lists.sr.ht
      prev_pkgver=$(pacman -Si meta.sr.ht | grep Version | cut -d ':' -f2 | cut -d ' ' -f2)
      prev_pkgrel=$(printf "%s" "$prev_pkgver" | cut -d'-' -f2)
      prev_pkgver=$(printf "%s" "$prev_pkgver" | cut -d'-' -f1)
      if [ "$prev_pkgver" == "$pkgver" ]
      then
        pkgrel=$(expr "$prev_pkgrel" + 1)
      else
        pkgrel=1
      fi
      sed -e "s/pkgver=.*/pkgver=$pkgver/" -i PKGBUILD
      sed -e "s/pkgrel=.*/pkgrel=$pkgrel/" -i PKGBUILD
      echo "pkgrel=$pkgrel" >> ~/.buildenv
      updpkgsums
      makepkg --config ../makepkg.conf -s --noconfirm
      cd ~/lists.sr.ht
      git describe --exact-match HEAD || complete-build
  - deploy: |
      cd sr.ht-pkgbuilds/lists.sr.ht
      sshopts="-o StrictHostKeyChecking=no"
      rsync --blocking-io \
        --rsh="ssh $sshopts" -rP *.pkg.tar.xz{,.sig} $repo_server:$repo_path/
      ssh $sshopts $repo_server repo-add -n -R \
        $repo_path/sr.ht.db.tar.gz \
        $repo_path/lists.sr.ht-$pkgver-$pkgrel-any.pkg.tar.xz
      ssh $sshopts $master sudo /usr/local/bin/update-srht lists.sr.ht
      ssh $sshopts $mailer sudo /usr/local/bin/update-srht lists.sr.ht
